### ISSUE TITLE
Getting Error: Cannot find module '.' when calling trello-backup

### ISSUE THREAD

**Issue by bsarvari** [jakutis/trello-backup#1]
Hi,

After following the installation steps (https://www.npmjs.com/package/trello-backup) I tried running your script but got the following issue. Any idea how to fix this?

```
$ trello-backup config.json 
module.js:338
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bsarvari/.npm-packages/lib/node_modules/trello-backup/lib/cli.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jakutis** [comment]
Hi @bsarvari, are you running trello-backup on node v0.12 or earlier?

**Comment by bsarvari** [comment]
Yes, it's v0.12.3
